//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.01 at 07:39:55 PM IST 
//


package com.erwin.cfx.connectors.pbi.map.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ItemLocation"/>
 *         &lt;element ref="{}StableEntries"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "itemLocation",
    "stableEntries"
})
@XmlRootElement(name = "Item")
public class Item {

    @XmlElement(name = "ItemLocation", required = true)
    protected ItemLocation itemLocation;
    @XmlElement(name = "StableEntries", required = true)
    protected StableEntries stableEntries;

    /**
     * Gets the value of the itemLocation property.
     * 
     * @return
     *     possible object is
     *     {@link ItemLocation }
     *     
     */
    public ItemLocation getItemLocation() {
        return itemLocation;
    }

    /**
     * Sets the value of the itemLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemLocation }
     *     
     */
    public void setItemLocation(ItemLocation value) {
        this.itemLocation = value;
    }

    /**
     * Gets the value of the stableEntries property.
     * 
     * @return
     *     possible object is
     *     {@link StableEntries }
     *     
     */
    public StableEntries getStableEntries() {
        return stableEntries;
    }

    /**
     * Sets the value of the stableEntries property.
     * 
     * @param value
     *     allowed object is
     *     {@link StableEntries }
     *     
     */
    public void setStableEntries(StableEntries value) {
        this.stableEntries = value;
    }

}
